### ISSUE TITLE
Did ForceUTF8 ensures only *.cs files?

### ISSUE THREAD

**Issue by marchenko1985** [vilic/vs-force-utf8#1]
It seems that ForceUTF8 forces utf-8 only for *.cs files.

https://github.com/vilic/vs-force-utf8/blob/master/ForceUTF8Package.cs#L73

Can we some how forse utf for all files (or may be have some configuration options)

**Comment by vilicvane** [comment]
It's for all text files. That UID stands more than *.cs files.

**Comment by marchenko1985** [comment]
We have tried on ascx file in windows-1251 encoding with no luck.

Can I somehow check does plugin runs on save? Or may be give you some more info?

**Comment by vilicvane** [comment]
Hi, the extension will only try to change the encoding if the file failed loading using UTF-8. Otherwise, it will keep it as is (since it can't tell whether it's really not a UTF-8 file).

**Comment by marchenko1985** [comment]
Oh I see now. Sorry, it seems that we have misunderstud your extension purpose.

**Comment by vilicvane** [comment]
Though I do find some issue with this extension through your feedback. And thanks. :D
