### ISSUE TITLE
How to make it support VS2017?

### ISSUE THREAD

**Issue by sotex** [vilic/vs-force-utf8#2]
Thank you for providing such a great program。
Is there a way to support it VS2017?

**Comment by 1vanK** [comment]
1) Download ForceUTF8.vsix from https://marketplace.visualstudio.com/items?itemName=vilicvane.ForceUTF8
2) Rename to zip
3) Extract
4) In file extension.vsixmanifest change
```
<InstallationTarget Version="[12.0,14.0]" Id="Microsoft.VisualStudio.Pro" />
```
to
```
<InstallationTarget Version="[12.0,)" Id="Microsoft.VisualStudio.Pro" />
```
5) Save
6) Pack all to zip
7) Rename to vsix
8) Install

**Comment by sotex** [comment]
I'm using VS2019 now, and now I'm using this extension below.
[forceallutf8](https://marketplace.visualstudio.com/items?itemName=LancelotChen.lancelotchen-forceallutf8)
